language: php

php:
    - 7.2
    - 7.3
    - 7.4

env:
    - COMPOSER_FLAGS="--prefer-lowest"
    - COMPOSER_FLAGS=""

install:
    - composer update ${COMPOSER_FLAGS} --no-interaction --prefer-source
script:
    - vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover

after_script:
    - wget https://scrutinizer-ci.com/ocular.phar
    - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
